### ISSUE TITLE
Cannot deploy a new environment in a different region

### ISSUE THREAD

**Issue by virilc** [aws-samples/aws-scalable-big-blue-button-example#112]
**Describe the bug**
Initially deployed to ap-southeast-1. Tried deploying another in another region, ap-northeast-1, error: "The following resource(s) failed to create: [BBBGreenlightTaskExecutionRole, BBBScaleliteExecutionRole]". Suspecting another possible cause deployment failure, which is "BBBApplicationEC2Role".

**To Reproduce**
1. Deploy the scalable BBB in one region.
2. Deploy in another. It will fail because IAM (Roles) are global.

**Expected behavior**
Deployment will be successful with no conflicts.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS M1 11.6.5
 - Browser: Firefox
 - Version: 91.8.0esr (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by couchgott** [comment]
hey, 

yes this hasn't been tested. i mean to deploy in diff regions but same account
i would go multi-account ;) 
anyways. let me tryout what we need to change to get it deploying multiple times into the same account. i guess reusing existing or generating the names of the roles you found is a good starting point

cheers,

**Comment by jonnyfux** [comment]
We run into the same issue because we wanted to deploy it into a different region for testing. We changed the following names to get it to work. Hope that helps as a workaround. @couchgott I think an easy fix would be to just append the aws region to these values to make it work without any modifications from the user.

_bbb-on-aws-params.json_
- BBBDBName
- BBBEnvironmentName

_bbb-on-aws-bbbappsingle.template.yaml /scalable_
- BBBApplicationEC2Role 

 _bbb-on-aws-frontendapp.template.yaml_
- BBBScaleliteExecutionRole
- BBBGreenlightTaskExecutionRole
- BBBFrontendALBDNS - RecordSets - Name (conference..${BBBDomainName})
- BBBScaleliteALBDNSName - RecordSets - name (scalelite.${BBBDomainName})
- BIGBLUEBUTTON_ENDPOINT to match new BBBScaleliteALBDNSName
- REDIS_URL URL_HOST to match new BBBScaleliteALBDNSName

**Comment by couchgott** [comment]
Hey, 

i think the DB name can be generated. the fixed version has been implemented at a very early stage. 
BBBScaleliteExecutionRole
BBBGreenlightTaskExecutionRole
these should be generated as well.

i am unsure about the endpoint names though. this could be done via utilizing subdomains .... or maybe just also offer parameters to the user to alter .. so they can choose to use "conference" or any other. 

BBBScaleliteALBDNSName this should be also generated i guess ... 
let me think how ^^

**Comment by couchgott** [comment]
so. just generating DBName would be kind of a hack via SecretsManager. 
Not even sure if it is needed as the DBName is utilizing the stack-name as well. 
we do need to give the stack-name static anyways but unified for each deployment. so i do not see an issue here tbh. 
so users do not even need to alter it for multi-deployments. 
aditionally if you use diff. regions you can have actually even the same stack and db name as they're purely regional. 
adding the region name might be good for sorting but not having it does not break anything.

**Comment by couchgott** [comment]
Hey folks, 

this should be now easily (or more easily) doable. Multi-Region or Single-Region Multi-Deployment in the same Account. 

BBBFrontendALBDNS - RecordSets - Name (conference..${BBBDomainName})
BBBScaleliteALBDNSName - RecordSets - name (scalelite.${BBBDomainName})
BIGBLUEBUTTON_ENDPOINT to match new BBBScaleliteALBDNSName
REDIS_URL URL_HOST to match new BBBScaleliteALBDNSName

i left as it is. i think using different subdomains for each setup is the way to go here. 

conference.teamA.bbb.example.com
conference.teamB.bbb.example.com

and so on. 
from my perspective this is simple and straight forward. 


feel free to test and reopen if you still run into issues. comments welcome ;)
