### ISSUE TITLE
Serverless Infrastructure for BigBlueButton and Turn Server

### ISSUE THREAD

**Issue by ojhaashish13** [aws-samples/aws-scalable-big-blue-button-example#127]
In the current setup, BigBlueButton Application and Turn server deployment using EC2 instances.
How I can create a complete serverless infrastructure where these 2 servers can migrate on AWS Fargate.

If you can guide me on the infrastructure level and can give me ideas then will try to implement them.

**Comment by couchgott** [comment]
Hi @ojhaashish13 , 

i would like to do that too. 
That said. It is quite a challenge and basically not possible to get BBB running within AWS Fargate due certain NET_* admin permissions BBB needs to manage ports/etc. 
What would be possible is to run BBB within containers on EC2 based ECS clusters. 
That said it needs quite some changes. Additionally the BBB project itself does provide some images since a short period of time but they're basically out of any documentation/support making me to have withdrawn this for now until the use/support gets more mature. 

Best, 

David

**Comment by couchgott** [comment]
HI @ojhaashish13 , 

with version 5.0.0 the need of the additional turn servers have been eliminated (due BigBlueButton 2.6.0). 
As Mentioned before, BBB will not be able to be used on AWS Fargate du some priviliges the docker based install needs which cannot be used. 
The BBB team is working on a docker image based version here: https://github.com/bigbluebutton/docker which is still  more like an alpha state. but it might give you an idea how a containerized setup would be look like. 
This would be possible with EC2 based ECS clusters. But while reading through the docker-compose.yml i do currently see no benefit utilizing it as there is no real benefit at the moment compaired with the script installer. 
So closing it here for now, but i will come back to evaluate the progress of the BBB project.
